#Este archivo docker-compose.yml tiene la función de definir y gestionar la configuración de
#una aplicación compuesta por múltiples contenedores Docker.

version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code