# Generated by Django 4.2.11 on 2024-07-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.CharField(db_comment='Descripción del Modelo de Vehículo', max_length=50)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctrl_comb.mark')),
            ],
            options={
                'verbose_name_plural': 'Modelos',
                'db_table_comment': 'Modelos de Vehículos',
            },
        ),
    ]
