# Generated by Django 4.2.11 on 2024-10-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0002_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'permissions': [('permiso_especial', 'Puede leer y editar Modelos')], 'verbose_name_plural': 'Modelos'},
        ),
    ]
