# Generated by Django 4.2.11 on 2024-10-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0005_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('MOT', 'Motocicleta'), ('CAP', 'Caponera'), ('SUV', 'Camionta SUV'), ('PIK', 'PickUp'), ('SED', 'Sedan'), ('TAX', 'Taxi'), ('MIC', 'Microbús'), ('BUS', '(Auto)BUS'), ('CAM', 'Camión')], default='SED', max_length=3),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='unidad_medida',
            field=models.IntegerField(choices=[(1, 'Galones'), (2, 'Litros')], default=1),
        ),
    ]
